// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class equipmentlocationfieldadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(equipmentlocationfieldadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712201746382_equipment-location-field-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
