// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newdateformat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdateformat));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141146438_new-date-format"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
