// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class transactionmodelupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactionmodelupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201802052107115_transaction-model-updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
