// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfluentconfiguration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfluentconfiguration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241234384_new-fluent-configuration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
