// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newfluentconfiguration3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newfluentconfiguration3));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241238129_new-fluent-configuration3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
