// <auto-generated />
namespace EquipmentDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class purchasedaddedtotransactiontype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(purchasedaddedtotransactiontype));
        
        string IMigrationMetadata.Id
        {
            get { return "201802111402054_purchased-added-to-transaction-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
